version: 1.0.{build}

skip_commits:
  files:
    - .travis.yml
    - '**/*.md'

image:
  - Visual Studio 2019

matrix:
  fast_finish: true

install:
  - pip install conan

platform:
  - x64

configuration:
  - Debug
  - Release

build:
  parallel: true
  verbosity: minimal

before_build:
  - mkdir -p build && cd build
  - conan install .. --build missing -s build_type=Debug
  - conan install .. --build missing -s build_type=Release
  - cmake -G "Visual Studio 16 2019" -A x64 ..

build_script:
  - cmake --build . --config %CONFIGURATION%

after_build:
  - ctest --extra-verbose -C %CONFIGURATION%
