language: cpp

sudo: false
notifications:
  email: false

os: linux
dist: bionic

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:

    #############################################################################
    # Clang on macOS
    #

    - os: osx
      env:
        - CXX_COMPILER=clang++
        - BUILD_TYPE=Release
      osx_image: xcode11.3
      compiler: clang

    - os: osx
      env:
        - CXX_COMPILER=clang++
        - BUILD_TYPE=Debug
      osx_image: xcode11.3
      compiler: clang

    #############################################################################
    # GCC on Linux
    #

    - env:
        - JOB="GCC 7 Release"
        - CXX_COMPILER=g++-7
        - BUILD_TYPE=Release
      addons: &gcc7
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - env:
        - JOB="GCC 7 Debug"
        - CXX_COMPILER=g++-7
        - BUILD_TYPE=Debug
      addons: *gcc7

install:
  # Set the ${CXX} variable properly.
  - export CXX=${CXX_COMPILER}
  - ${CXX} --version
  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/.
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  # Travis machines have 2 cores
  - JOBS=2
  # Install the latest CMake (unless already installed on macOS).
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      CMAKE_VERSION=3.16.5
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew update
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version
  # Install Conan package manager.
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo pip install conan
    else
      brew install conan || brew upgrade conan
    fi
  - conan profile new default --detect
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      conan profile update settings.compiler.libcxx=libstdc++11 default
    fi
  - conan --version
  - conan profile show default

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - conan install .. --build missing -s build_type=Debug
  - conan install .. --build missing -s build_type=Release
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - cmake --build . --config $BUILD_TYPE -- -j${JOBS}
